### ISSUE TITLE
add EqualInteger api

### ISSUE THREAD

**Issue by ddkwork** [peterldowns/testy#1]
![Screenshot_20241107_024506_com.realvnc.viewer.android.jpg](https://github.com/user-attachments/assets/c04d84ae-222f-4bdf-b710-1b477056ef40)

I have a lot of unit tests that need to constrain integer types, and I'm not sure if I should add both signed and unsigned api's, but this EqualInteger api will not use predefined variables. I know it may break the original pattern of the api, but for me adding this api will allow me to write a lot less lines of code within the unit tests, thank you for this great project!

**Comment by peterldowns** [comment]
Sorry, I don't understand. Can you please share a code example, not a screenshot, showing some examples of the assertions you would like to make and how you're unable to do it with the current helpers? The entire point of testy is that comparing two values of different types is almost certainly invalid.

Right now, if you want to compare two values that are both the same integer type, you can just use `assert.Equal`. If you want to compare two values that are both integers but of different types, you must explicitly convert the types, [just like the golang docs describe](https://go.dev/ref/spec#Numeric_types):

> Explicit conversions are required when different numeric types are mixed in an expression or assignment. For instance, int32 and int are not the same type even though they may have the same size on a particular architecture.

**Comment by ddkwork** [comment]
Sorry for my bad English, I also know that I need to show type conversion, what I want to describe is:Let the call to testy be made so that it tells me that I need to convert the type before compiling instead of after compiling when I realize that the type is wrong.
I haven't gotten around to updating tesy in this file
https://github.com/ddkwork/asm/blob/master/demo%2Fdemo.go

I basically forgot to convert the types when I first called the Equal function, which told me I needed to convert the types after the Equal function had compiled. Ideally it would tell me the type mismatch when calling Equal rather than waiting until after compilation to report an error, so it needs to be EqualInteger?EqualUint32?I'm not sure this is appropriate as it adds a lot of functions.

**Comment by peterldowns** [comment]
The code you linked is still using `testify/assert`, not `testy/assert`. The entire point of this library, testy, is that comparing two values of unequal types will give you a compilation error. You can do this right now by using `assert.Equal` or `check.Equal`.

If you are writing a test comparing two literals, not two variables, the go compiler *will* infer a valid type when possible, so do note that `assert.Equal(t, 1, .1)` will pass because the inferred type of the variables will be `float`, not `int`.
